version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "aioresponses"
          - "prek"
          - "pytest-asyncio"
          - "pytest-cov"
          - "pytest-error-for-skips"
          - "pytest-timeout"
          - "pytest"
          - "ruff"
          - "syrupy"
          - "ty"
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "orjson"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pre-commit"
    directory: "/"
