version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "aioresponses"
          - "prek"
          - "pytest"
          - "pytest-*"
          - "ruff"
          - "syrupy"
          - "ty"
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "orjson"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns: ["*"]
